### ISSUE TITLE
Simple click

### ISSUE THREAD

**Issue by ghost** [artistech-inc/tuio-mouse-driver#1]
Hi,
I was wandering if this software could be used so 1 finger was left click and you could keep it held down for something like paint.

Thanks,
Tom

**Comment by ZenHarbinger** [comment]
Yes, as is; one finger is mouse movement, the second will simulate a click.  As long as there are 2 registered touches, it will simulate the left click down.

**Comment by ghost** [comment]
Yes I understand but was wandering if you would be kind enough to alter it so one finger was click and drag, not 2

Thanks,
Tom

**Comment by ZenHarbinger** [comment]
No, won't do that as that is not the functionality.  If you want that, you will need to fork and implement the changes.  Sorry.
